# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dbetaPT <- function(x, alpha) {
    .Call(`_RiVIERA_dbetaPT`, x, alpha)
}

inferPri <- function(ann, ann_w, ann_w0) {
    .Call(`_RiVIERA_inferPri`, ann, ann_w, ann_w0)
}

inferPriByLoci <- function(ann, ann_w, ann_w0, locusCursor) {
    .Call(`_RiVIERA_inferPriByLoci`, ann, ann_w, ann_w0, locusCursor)
}

rwishart <- function(nu, V) {
    .Call(`_RiVIERA_rwishart`, nu, V)
}

isPosDef <- function(x) {
    .Call(`_RiVIERA_isPosDef`, x)
}

dmvnrm <- function(x, mu, sigma, logd = TRUE) {
    .Call(`_RiVIERA_dmvnrm`, x, mu, sigma, logd)
}

dmvnrm_lambda <- function(x, mu, lambda, logd = TRUE) {
    .Call(`_RiVIERA_dmvnrm_lambda`, x, mu, lambda, logd)
}

fastInv <- function(x) {
    .Call(`_RiVIERA_fastInv`, x)
}

duvnrm <- function(x, mu = 0, s2 = 1) {
    .Call(`_RiVIERA_duvnrm`, x, mu, s2)
}

createLocusCursor <- function(ldmat_list, totalSNPs) {
    .Call(`_RiVIERA_createLocusCursor`, ldmat_list, totalSNPs)
}

normalizeZscoreByLoci <- function(zscore, locusCursor) {
    .Call(`_RiVIERA_normalizeZscoreByLoci`, zscore, locusCursor)
}

estimateParByEM <- function(pval, alpha_init = 0.1, pri0_init = 1e-3, minPval = 1e-30, thres = 1e-3, max_iter = 1e3L) {
    .Call(`_RiVIERA_estimateParByEM`, pval, alpha_init, pri0_init, minPval, thres, max_iter)
}

calGradW_l <- function(ann, configs, configs_post, ann_w, ann_w_mu, ann_w_lambda, ann_w0, ann_w0_mu, ann_w0_tau) {
    .Call(`_RiVIERA_calGradW_l`, ann, configs, configs_post, ann_w, ann_w_mu, ann_w_lambda, ann_w0, ann_w0_mu, ann_w0_tau)
}

calGradW <- function(ann, configs_list, configs_post_list, locusCursor, ann_w, ann_w_mu, ann_w_lambda, ann_w0, ann_w0_mu, ann_w0_tau) {
    .Call(`_RiVIERA_calGradW`, ann, configs_list, configs_post_list, locusCursor, ann_w, ann_w_mu, ann_w_lambda, ann_w0, ann_w0_mu, ann_w0_tau)
}

calGrad_dEdV <- function(x, sigma) {
    .Call(`_RiVIERA_calGrad_dEdV`, x, sigma)
}

calGrad_dEdS <- function(x, sigma, s) {
    .Call(`_RiVIERA_calGrad_dEdS`, x, sigma, s)
}

calGradS_l <- function(zscore, ldmat, configs, configs_post, s2) {
    .Call(`_RiVIERA_calGradS_l`, zscore, ldmat, configs, configs_post, s2)
}

calGradS <- function(zscore, ldmat_list, configs_list, configs_post_list, locusCursor, s2) {
    .Call(`_RiVIERA_calGradS`, zscore, ldmat_list, configs_list, configs_post_list, locusCursor, s2)
}

hmcS <- function(zscore, ldmat_list, configs_list, configs_post_list, locusCursor, s2_cur, step, nsteps, verbose, lbs2 = 1e-8, ubs2 = 1e3) {
    .Call(`_RiVIERA_hmcS`, zscore, ldmat_list, configs_list, configs_post_list, locusCursor, s2_cur, step, nsteps, verbose, lbs2, ubs2)
}

hmcW <- function(ann, configs_list, configs_post_list, locusCursor, ann_w_cur, ann_w_mu, ann_w_lambda, ann_w0_cur, ann_w0_mu, ann_w0_tau, step, nsteps, verbose) {
    .Call(`_RiVIERA_hmcW`, ann, configs_list, configs_post_list, locusCursor, ann_w_cur, ann_w_mu, ann_w_lambda, ann_w0_cur, ann_w0_mu, ann_w0_tau, step, nsteps, verbose)
}

inferConfigs_imp <- function(proposal, zscore, ldmat, ann, ann_w, ann_w0, s2, sampleSize, verbose) {
    .Call(`_RiVIERA_inferConfigs_imp`, proposal, zscore, ldmat, ann, ann_w, ann_w0, s2, sampleSize, verbose)
}

inferConfigs_nbh <- function(zscore, ldmat, ann, ann_w, ann_w0, s2, sampleSize, verbose) {
    .Call(`_RiVIERA_inferConfigs_nbh`, zscore, ldmat, ann, ann_w, ann_w0, s2, sampleSize, verbose)
}

inferConfigsAllLoci <- function(proposal, zscore, ldmat_list, locusCursor, ann, ann_w, ann_w0, s2, sampleSize, sampleScheme, verbose = FALSE) {
    .Call(`_RiVIERA_inferConfigsAllLoci`, proposal, zscore, ldmat_list, locusCursor, ann, ann_w, ann_w0, s2, sampleSize, sampleScheme, verbose)
}

inferPPA <- function(pval, ann, ann_w, ann_w0 = -4.6, alpha = 0.1, minPval = 1e-30) {
    .Call(`_RiVIERA_inferPPA`, pval, ann, ann_w, ann_w0, alpha, minPval)
}

inferPPAByLoci <- function(zscore, ann, ann_w, ann_w0, s2, locusCursor) {
    .Call(`_RiVIERA_inferPPAByLoci`, zscore, ann, ann_w, ann_w0, s2, locusCursor)
}

initParams <- function(zscoreList, annList, ldmatList, locusCursorList, causalCntPerLocusPrior, s2_init, pri0 = 1e-2) {
    .Call(`_RiVIERA_initParams`, zscoreList, annList, ldmatList, locusCursorList, causalCntPerLocusPrior, s2_init, pri0)
}

lprW <- function(ann, configs_list, configs_post_list, locusCursor, ann_w, ann_w_mu, ann_w_lambda, ann_w0, ann_w0_mu, ann_w0_tau) {
    .Call(`_RiVIERA_lprW`, ann, configs_list, configs_post_list, locusCursor, ann_w, ann_w_mu, ann_w_lambda, ann_w0, ann_w0_mu, ann_w0_tau)
}

lprS_l <- function(zscore, ldmat, configs, configs_post, s2) {
    .Call(`_RiVIERA_lprS_l`, zscore, ldmat, configs, configs_post, s2)
}

nbh <- function(config, m) {
    .Call(`_RiVIERA_nbh`, config, m)
}

riviera_fmap <- function(zscore, ldmat_list, ann, ann_w_mu, ann_w_sigma0, configSampleScheme = 1L, c0 = 1.0, pri0_init = 1e-2, s2_init = 1, burninFrac = 0.2, sampleSize = 1e3L, maxConfig = 1e6L, max_iter = 1e3L, step_W = 0.01, nsteps_W = 100L, step_S = 0.01, nsteps_S = 100L, thres = 1e-3, verbose = TRUE, verboseC = TRUE, verboseS = TRUE, verboseW = TRUE) {
    .Call(`_RiVIERA_riviera_fmap`, zscore, ldmat_list, ann, ann_w_mu, ann_w_sigma0, configSampleScheme, c0, pri0_init, s2_init, burninFrac, sampleSize, maxConfig, max_iter, step_W, nsteps_W, step_S, nsteps_S, thres, verbose, verboseC, verboseS, verboseW)
}

calGradPT_glass <- function(pri, ppa, ann, ann_w, ann_w0, ann_w0_mu, groupMat, sdf) {
    .Call(`_RiVIERA_calGradPT_glass`, pri, ppa, ann, ann_w, ann_w0, ann_w0_mu, groupMat, sdf)
}

calHessPT_glass <- function(pri, ann, ann_w, groupMat, sdf) {
    .Call(`_RiVIERA_calHessPT_glass`, pri, ann, ann_w, groupMat, sdf)
}

lprPT_glass <- function(pval, pri, ann, alpha, ann_w, ann_w0, ann_w0_mu, groupMat, sdf) {
    .Call(`_RiVIERA_lprPT_glass`, pval, pri, ann, alpha, ann_w, ann_w0, ann_w0_mu, groupMat, sdf)
}

lprPT_glass_givenPPA <- function(pval, pri, ppa, alpha, ann_w, ann_w0, ann_w0_mu, groupMat, sdf) {
    .Call(`_RiVIERA_lprPT_glass_givenPPA`, pval, pri, ppa, alpha, ann_w, ann_w0, ann_w0_mu, groupMat, sdf)
}

printAnn <- function(x, activeGroupIdx, groupScores) {
    invisible(.Call(`_RiVIERA_printAnn`, x, activeGroupIdx, groupScores))
}

riviera_glass <- function(pval, ann, groupMat, targetGroups, targetGroupNames, minPval = 1e-30, alpha0 = 0.1, pri0 = 1e-3, epsilon = 1e-2, thres = 1e-3, max_iter = 1e3L, minAlpha = 1e-30, maxAlpha = 0.5, groupScoreThres = 0.1, verbose = 1L) {
    .Call(`_RiVIERA_riviera_glass`, pval, ann, groupMat, targetGroups, targetGroupNames, minPval, alpha0, pri0, epsilon, thres, max_iter, minAlpha, maxAlpha, groupScoreThres, verbose)
}

calGradPT_ridge <- function(pri, ppa, ann, ann_w, ann_w_mu, ann_w0, ann_w0_mu) {
    .Call(`_RiVIERA_calGradPT_ridge`, pri, ppa, ann, ann_w, ann_w_mu, ann_w0, ann_w0_mu)
}

calHessPT_ridge <- function(pri, ann) {
    .Call(`_RiVIERA_calHessPT_ridge`, pri, ann)
}

lprPT_ridge <- function(pval, pri, ann, alpha, ann_w, ann_w_mu, ann_w0, ann_w0_mu) {
    .Call(`_RiVIERA_lprPT_ridge`, pval, pri, ann, alpha, ann_w, ann_w_mu, ann_w0, ann_w0_mu)
}

lprPT_givenPPA_ridge <- function(pval, pri, ppa, ann, alpha, ann_w, ann_w_mu, ann_w0, ann_w0_mu) {
    .Call(`_RiVIERA_lprPT_givenPPA_ridge`, pval, pri, ppa, ann, alpha, ann_w, ann_w_mu, ann_w0, ann_w0_mu)
}

riviera_ridge <- function(pval, ann, ann_w_mu, minPval = 1e-30, alpha0 = 0.1, pri0 = 0.1, epsilon = 1e-5, thres = 1e-3, max_iter = 1e3L, minAlpha = 1e-30, maxAlpha = 0.5, fitAlpha = TRUE) {
    .Call(`_RiVIERA_riviera_ridge`, pval, ann, ann_w_mu, minPval, alpha0, pri0, epsilon, thres, max_iter, minAlpha, maxAlpha, fitAlpha)
}

eval_lld <- function(zscore, ldmat, s2) {
    .Call(`_RiVIERA_eval_lld`, zscore, ldmat, s2)
}

eval_pri <- function(ann, causalidx, ann_w, ann_w0, logd = TRUE) {
    .Call(`_RiVIERA_eval_pri`, ann, causalidx, ann_w, ann_w0, logd)
}

find_uniqueRows <- function(x) {
    .Call(`_RiVIERA_find_uniqueRows`, x)
}

sampleConfigs <- function(proposal, sampleSize) {
    .Call(`_RiVIERA_sampleConfigs`, proposal, sampleSize)
}

sampleAnnLambda <- function(wishart_df, ann_w_sigma0, ann_w) {
    .Call(`_RiVIERA_sampleAnnLambda`, wishart_df, ann_w_sigma0, ann_w)
}

sampleAnnBiasTau <- function(ann_w0, ann_w0_mu, alpha = 1, beta = 1) {
    .Call(`_RiVIERA_sampleAnnBiasTau`, ann_w0, ann_w0_mu, alpha, beta)
}

